cp splitFasta.py EOG80044P
cp splitFasta.py EOG80044Q
cp splitFasta.py EOG80044T
cp splitFasta.py EOG8030CD
cp splitFasta.py EOG8030CG
cp splitFasta.py EOG8030CJ
cp splitFasta.py EOG8030CM
cp splitFasta.py EOG8030CR
cp splitFasta.py EOG8030CV
cp splitFasta.py EOG8030CW
cp splitFasta.py EOG8030D4
cp splitFasta.py EOG805VMC
cp splitFasta.py EOG805VMF
cp splitFasta.py EOG805VMH
cp splitFasta.py EOG805VMJ
cp splitFasta.py EOG805VMN
cp splitFasta.py EOG805VMS
cp splitFasta.py EOG805VMV
cp splitFasta.py EOG805VN0
cp splitFasta.py EOG808QV3
cp splitFasta.py EOG808QV4
cp splitFasta.py EOG808QV5
cp splitFasta.py EOG808QV7
cp splitFasta.py EOG808QV9
cp splitFasta.py EOG808QVC
cp splitFasta.py EOG808QVG
cp splitFasta.py EOG808QVK
cp splitFasta.py EOG80CM36
cp splitFasta.py EOG80CM38
cp splitFasta.py EOG80CM3J
cp splitFasta.py EOG80GG9Z
cp splitFasta.py EOG80GGB6
cp splitFasta.py EOG80GGBM
cp splitFasta.py EOG80GGBV
cp splitFasta.py EOG80KBK0
cp splitFasta.py EOG80KBK2
cp splitFasta.py EOG80KBK7
cp splitFasta.py EOG80KBKC
cp splitFasta.py EOG80KBKD
cp splitFasta.py EOG80KBKG
cp splitFasta.py EOG80KBKK
cp splitFasta.py EOG80KBKP
cp splitFasta.py EOG80P6SZ
cp splitFasta.py EOG80P6T0
cp splitFasta.py EOG80P6T3
cp splitFasta.py EOG80P6TB
cp splitFasta.py EOG80P6TS
cp splitFasta.py EOG80S31X
cp splitFasta.py EOG80S321
cp splitFasta.py EOG80S322
cp splitFasta.py EOG80S326
cp splitFasta.py EOG80S327
cp splitFasta.py EOG80S32J
cp splitFasta.py EOG80VZ8R
cp splitFasta.py EOG80VZ8T
cp splitFasta.py EOG80VZ94
cp splitFasta.py EOG80VZ99
cp splitFasta.py EOG80ZTHS
cp splitFasta.py EOG80ZTHW
cp splitFasta.py EOG80ZTHX
cp splitFasta.py EOG80ZTHZ
cp splitFasta.py EOG80ZTJ0
cp splitFasta.py EOG80ZTJ2
cp splitFasta.py EOG80ZTJ5
cp splitFasta.py EOG80ZTJ6
cp splitFasta.py EOG80ZTJF
cp splitFasta.py EOG80ZTJH
cp splitFasta.py EOG812PRN
cp splitFasta.py EOG812PRR
cp splitFasta.py EOG812PRS
cp splitFasta.py EOG812PS0
cp splitFasta.py EOG812PS1
cp splitFasta.py EOG812PS2
cp splitFasta.py EOG812PSK
cp splitFasta.py EOG815K0M
cp splitFasta.py EOG815K0R
cp splitFasta.py EOG815K0W
cp splitFasta.py EOG815K0X
cp splitFasta.py EOG815K10
cp splitFasta.py EOG815K11
cp splitFasta.py EOG818F7M
cp splitFasta.py EOG818F7Q
cp splitFasta.py EOG818F7R
cp splitFasta.py EOG818F81
cp splitFasta.py EOG81C9GC
cp splitFasta.py EOG81C9GG
cp splitFasta.py EOG81C9GH
cp splitFasta.py EOG81C9GK
cp splitFasta.py EOG81C9GN
cp splitFasta.py EOG81C9H1
cp splitFasta.py EOG81C9H4
cp splitFasta.py EOG81G5QB
cp splitFasta.py EOG81G5QC
cp splitFasta.py EOG81G5QT
cp splitFasta.py EOG81K1ZC
cp splitFasta.py EOG81K1ZF
cp splitFasta.py EOG81K1ZM
cp splitFasta.py EOG81K1ZN
cp splitFasta.py EOG81K1ZP
cp splitFasta.py EOG81K200
cp splitFasta.py EOG81NX66
cp splitFasta.py EOG81NX67
cp splitFasta.py EOG81NX6D
cp splitFasta.py EOG81NX6F
cp splitFasta.py EOG81NX6M
cp splitFasta.py EOG81NX74
cp splitFasta.py EOG81RSF4
cp splitFasta.py EOG81RSF6
cp splitFasta.py EOG81RSF8
cp splitFasta.py EOG81RSFH
cp splitFasta.py EOG81RSFW
cp splitFasta.py EOG81VNP3
cp splitFasta.py EOG81VNPF
cp splitFasta.py EOG81VNPR
cp splitFasta.py EOG81ZHX4
cp splitFasta.py EOG81ZHX6
cp splitFasta.py EOG81ZHX9
cp splitFasta.py EOG81ZHXF
cp splitFasta.py EOG81ZHXJ
cp splitFasta.py EOG81ZHXR
cp splitFasta.py EOG822D4Z
cp splitFasta.py EOG822D53
cp splitFasta.py EOG822D56
cp splitFasta.py EOG822D5J
cp splitFasta.py EOG822D5V
cp splitFasta.py EOG8258CW
cp splitFasta.py EOG8258CZ
cp splitFasta.py EOG8258D2
cp splitFasta.py EOG8258D4
cp splitFasta.py EOG8258D9
cp splitFasta.py EOG8284MS
cp splitFasta.py EOG8284MZ
cp splitFasta.py EOG8284N3
cp splitFasta.py EOG8284N5
cp splitFasta.py EOG8284NB
cp splitFasta.py EOG8284NC
cp splitFasta.py EOG8284NM
cp splitFasta.py EOG82C0VS
cp splitFasta.py EOG82C0VV
cp splitFasta.py EOG82C0VW
cp splitFasta.py EOG82C0W1
cp splitFasta.py EOG82C0W2
cp splitFasta.py EOG82C0W6
cp splitFasta.py EOG82C0WF
cp splitFasta.py EOG82FW3M
cp splitFasta.py EOG82FW3N
cp splitFasta.py EOG82FW3P
cp splitFasta.py EOG82FW3S
cp splitFasta.py EOG82FW3T
cp splitFasta.py EOG82FW41
cp splitFasta.py EOG82FW44
cp splitFasta.py EOG82FW46
cp splitFasta.py EOG82FW48
cp splitFasta.py EOG82JRBN
cp splitFasta.py EOG82JRBP
cp splitFasta.py EOG82JRBQ
cp splitFasta.py EOG82JRBR
cp splitFasta.py EOG82JRBV
cp splitFasta.py EOG82JRBZ
cp splitFasta.py EOG82NMKF
cp splitFasta.py EOG82NMKG
cp splitFasta.py EOG82NMKH
cp splitFasta.py EOG82NMKM
cp splitFasta.py EOG82NMKP
cp splitFasta.py EOG82NMKR
cp splitFasta.py EOG82NMKX
cp splitFasta.py EOG82NMM2
cp splitFasta.py EOG82NMMD
cp splitFasta.py EOG82RGTF
cp splitFasta.py EOG82RGTH
cp splitFasta.py EOG82RGTK
cp splitFasta.py EOG82RGTM
cp splitFasta.py EOG82RGTN
cp splitFasta.py EOG82RGTQ
cp splitFasta.py EOG82RGTS
cp splitFasta.py EOG82RGTV
cp splitFasta.py EOG82RGTZ
cp splitFasta.py EOG82RGV1
cp splitFasta.py EOG82RGV5
cp splitFasta.py EOG82VC2D
cp splitFasta.py EOG82VC2H
cp splitFasta.py EOG82VC2K
cp splitFasta.py EOG82VC35
cp splitFasta.py EOG82Z799
cp splitFasta.py EOG82Z79C
cp splitFasta.py EOG82Z79G
cp splitFasta.py EOG82Z79X
cp splitFasta.py EOG8323J7
cp splitFasta.py EOG8323JB
cp splitFasta.py EOG8323JD
cp splitFasta.py EOG8323JF
cp splitFasta.py EOG8323JH
cp splitFasta.py EOG8323JR
cp splitFasta.py EOG8323JW
cp splitFasta.py EOG834ZSB
cp splitFasta.py EOG834ZSD
cp splitFasta.py EOG834ZSJ
cp splitFasta.py EOG834ZST
cp splitFasta.py EOG834ZSX
cp splitFasta.py EOG834ZSZ
cp splitFasta.py EOG837V0Z
cp splitFasta.py EOG837V13
cp splitFasta.py EOG837V15
cp splitFasta.py EOG837V16
cp splitFasta.py EOG837V19
cp splitFasta.py EOG837V1G
cp splitFasta.py EOG837V1K
cp splitFasta.py EOG837V1Q
cp splitFasta.py EOG837V1T
cp splitFasta.py EOG83BQ86
cp splitFasta.py EOG83BQ8C
cp splitFasta.py EOG83BQ8N
cp splitFasta.py EOG83FKH1
cp splitFasta.py EOG83FKH2
cp splitFasta.py EOG83FKH4
cp splitFasta.py EOG83FKH7
cp splitFasta.py EOG83FKH8
cp splitFasta.py EOG83FKHF
cp splitFasta.py EOG83FKHH
cp splitFasta.py EOG83FKHN
cp splitFasta.py EOG83FKHP
cp splitFasta.py EOG83FKHX
cp splitFasta.py EOG83JFR3
cp splitFasta.py EOG83JFR6
cp splitFasta.py EOG83JFR7
cp splitFasta.py EOG83JFRB
cp splitFasta.py EOG83JFRC
cp splitFasta.py EOG83JFRF
cp splitFasta.py EOG83JFRJ
cp splitFasta.py EOG83N9ZT
cp splitFasta.py EOG83NB03
cp splitFasta.py EOG83NB0B
cp splitFasta.py EOG83R66W
cp splitFasta.py EOG83R67M
cp splitFasta.py EOG83V2FQ
cp splitFasta.py EOG83V2G4
cp splitFasta.py EOG83V2G9
cp splitFasta.py EOG83V2GB
cp splitFasta.py EOG83XXPM
cp splitFasta.py EOG83XXPR
cp splitFasta.py EOG83XXPS
cp splitFasta.py EOG83XXQ2
cp splitFasta.py EOG83XXQD
cp splitFasta.py EOG841SXM
cp splitFasta.py EOG841SXQ
cp splitFasta.py EOG841SXV
cp splitFasta.py EOG841SZ3
cp splitFasta.py EOG841SZ4
cp splitFasta.py EOG844P5G
cp splitFasta.py EOG844P5M
cp splitFasta.py EOG844P5N
cp splitFasta.py EOG844P5R
cp splitFasta.py EOG844P5S
cp splitFasta.py EOG844P5W
cp splitFasta.py EOG844P66
cp splitFasta.py EOG847JDF
cp splitFasta.py EOG847JDR
cp splitFasta.py EOG847JDS
cp splitFasta.py EOG847JDW
cp splitFasta.py EOG847JF2
cp splitFasta.py EOG847JF4
cp splitFasta.py EOG84BDND
cp splitFasta.py EOG84BDNH
cp splitFasta.py EOG84BDNN
cp splitFasta.py EOG84BDNV
cp splitFasta.py EOG84F8WN
cp splitFasta.py EOG84F8WP
cp splitFasta.py EOG84J546
cp splitFasta.py EOG84J549
cp splitFasta.py EOG84J54B
cp splitFasta.py EOG84J54F
cp splitFasta.py EOG84J54J
cp splitFasta.py EOG84J54Q
cp splitFasta.py EOG84J54W
cp splitFasta.py EOG84J550
cp splitFasta.py EOG84N1C7
cp splitFasta.py EOG84N1CJ
cp splitFasta.py EOG84N1CS
cp splitFasta.py EOG84N1CW
cp splitFasta.py EOG84QWM3
cp splitFasta.py EOG84QWMF
cp splitFasta.py EOG84QWMN
cp splitFasta.py EOG84TRV0
cp splitFasta.py EOG84TRV1
cp splitFasta.py EOG84TRV3
cp splitFasta.py EOG84TRV9
cp splitFasta.py EOG84TRVB
cp splitFasta.py EOG84TRVD
cp splitFasta.py EOG84TRVH
cp splitFasta.py EOG84TRVM
cp splitFasta.py EOG84TRVN
cp splitFasta.py EOG84TRVS
cp splitFasta.py EOG84XN2X
cp splitFasta.py EOG84XN31
cp splitFasta.py EOG84XN32
cp splitFasta.py EOG84XN36
cp splitFasta.py EOG84XN37
cp splitFasta.py EOG84XN39
cp splitFasta.py EOG84XN3C
cp splitFasta.py EOG84XN3F
cp splitFasta.py EOG84XN3K
cp splitFasta.py EOG851H9Z
cp splitFasta.py EOG851HB0
cp splitFasta.py EOG851HB1
cp splitFasta.py EOG851HB2
cp splitFasta.py EOG851HB6
cp splitFasta.py EOG851HBJ
cp splitFasta.py EOG851HBK
cp splitFasta.py EOG854CJS
cp splitFasta.py EOG854CJW
cp splitFasta.py EOG854CJX
cp splitFasta.py EOG854CJZ
cp splitFasta.py EOG854CK0
cp splitFasta.py EOG854CK1
cp splitFasta.py EOG854CK3
cp splitFasta.py EOG854CK7
cp splitFasta.py EOG854CK8
cp splitFasta.py EOG854CKP
cp splitFasta.py EOG8577SP
cp splitFasta.py EOG8577SX
cp splitFasta.py EOG8577SZ
cp splitFasta.py EOG8577TG
cp splitFasta.py EOG85B41Q
cp splitFasta.py EOG85B41R
cp splitFasta.py EOG85B41T
cp splitFasta.py EOG85B41V
cp splitFasta.py EOG85B41X
cp splitFasta.py EOG85B420
cp splitFasta.py EOG85B423
cp splitFasta.py EOG85B425
cp splitFasta.py EOG85B426
cp splitFasta.py EOG85B429
cp splitFasta.py EOG85B42D
cp splitFasta.py EOG85B42Q
cp splitFasta.py EOG85F08J
cp splitFasta.py EOG85F08M
cp splitFasta.py EOG85F08N
cp splitFasta.py EOG85F08P
cp splitFasta.py EOG85F08V
cp splitFasta.py EOG85F092
cp splitFasta.py EOG85HVHH
cp splitFasta.py EOG85HVHJ
cp splitFasta.py EOG85HVHP
cp splitFasta.py EOG85HVHT
cp splitFasta.py EOG85HVHW
cp splitFasta.py EOG85HVJ0
cp splitFasta.py EOG85HVJ9
cp splitFasta.py EOG85MQRJ
cp splitFasta.py EOG85MQRN
cp splitFasta.py EOG85MQRP
cp splitFasta.py EOG85MQRS
cp splitFasta.py EOG85MQRV
cp splitFasta.py EOG85MQRW
cp splitFasta.py EOG85MQS0
cp splitFasta.py EOG85QM0D
cp splitFasta.py EOG85QM0F
cp splitFasta.py EOG85QM0H
cp splitFasta.py EOG85QM0J
cp splitFasta.py EOG85QM0P
cp splitFasta.py EOG85QM14
cp splitFasta.py EOG85TG79
cp splitFasta.py EOG85TG7C
cp splitFasta.py EOG85TG7F
cp splitFasta.py EOG85TG7R
cp splitFasta.py EOG85TG7S
cp splitFasta.py EOG85XBG7
cp splitFasta.py EOG85XBGC
cp splitFasta.py EOG85XBGJ
cp splitFasta.py EOG85XBGX
cp splitFasta.py EOG85XBH0
cp splitFasta.py EOG85XBH5
cp splitFasta.py EOG8616Q4
cp splitFasta.py EOG8616Q6
cp splitFasta.py EOG8616Q7
cp splitFasta.py EOG8616QD
cp splitFasta.py EOG8616QG
cp splitFasta.py EOG8616QK
cp splitFasta.py EOG8616QP
cp splitFasta.py EOG8616QT
cp splitFasta.py EOG8616QZ
cp splitFasta.py EOG8642Z1
cp splitFasta.py EOG8642Z8
cp splitFasta.py EOG8642Z9
cp splitFasta.py EOG8642ZB
cp splitFasta.py EOG8642ZG
cp splitFasta.py EOG8642ZJ
cp splitFasta.py EOG8642ZQ
cp splitFasta.py EOG8642ZX
cp splitFasta.py EOG866Z69
cp splitFasta.py EOG866Z6G
cp splitFasta.py EOG866Z6H
cp splitFasta.py EOG866Z6K
cp splitFasta.py EOG866Z6X
cp splitFasta.py EOG869TDX
cp splitFasta.py EOG869TF7
cp splitFasta.py EOG869TF8
cp splitFasta.py EOG869TFD
cp splitFasta.py EOG869TFH
cp splitFasta.py EOG869TFW
cp splitFasta.py EOG86DPNV
cp splitFasta.py EOG86DPNZ
cp splitFasta.py EOG86DPP1
cp splitFasta.py EOG86DPP2
cp splitFasta.py EOG86DPP6
cp splitFasta.py EOG86DPP8
cp splitFasta.py EOG86DPPB
cp splitFasta.py EOG86DPPK
cp splitFasta.py EOG86DPPT
cp splitFasta.py EOG86DPPW
cp splitFasta.py EOG86HJWV
cp splitFasta.py EOG86HJWW
cp splitFasta.py EOG86HJX0
cp splitFasta.py EOG86HJX2
cp splitFasta.py EOG86HJX3
cp splitFasta.py EOG86HJX4
cp splitFasta.py EOG86HJXM
cp splitFasta.py EOG86HJXR
cp splitFasta.py EOG86MF4R
cp splitFasta.py EOG86MF4X
cp splitFasta.py EOG86MF4Z
cp splitFasta.py EOG86MF52
cp splitFasta.py EOG86MF53
cp splitFasta.py EOG86MF54
cp splitFasta.py EOG86MF5C
cp splitFasta.py EOG86MF5P
cp splitFasta.py EOG86Q9CS
cp splitFasta.py EOG86Q9D2
cp splitFasta.py EOG86Q9D3
cp splitFasta.py EOG86Q9D4
cp splitFasta.py EOG86Q9D5
cp splitFasta.py EOG86T5MS
cp splitFasta.py EOG86T5N4
cp splitFasta.py EOG86X1VH
cp splitFasta.py EOG86X1VT
cp splitFasta.py EOG86X1W2
cp splitFasta.py EOG86X1W6
cp splitFasta.py EOG870X3C
cp splitFasta.py EOG870X3H
cp splitFasta.py EOG870X3N
cp splitFasta.py EOG870X3S
cp splitFasta.py EOG870X3W
cp splitFasta.py EOG870X43
cp splitFasta.py EOG873SBG
cp splitFasta.py EOG873SBJ
cp splitFasta.py EOG873SBM
cp splitFasta.py EOG873SBQ
cp splitFasta.py EOG873SBW
cp splitFasta.py EOG876NKB
cp splitFasta.py EOG876NKH
cp splitFasta.py EOG876NKM
cp splitFasta.py EOG876NKN
cp splitFasta.py EOG876NKT
cp splitFasta.py EOG876NKV
cp splitFasta.py EOG876NKZ
cp splitFasta.py EOG876NM3
cp splitFasta.py EOG879HTD
cp splitFasta.py EOG879HTJ
cp splitFasta.py EOG879HTK
cp splitFasta.py EOG879HTM
cp splitFasta.py EOG879HTN
cp splitFasta.py EOG879HTP
cp splitFasta.py EOG879HTR
cp splitFasta.py EOG879HTS
cp splitFasta.py EOG879HTZ
cp splitFasta.py EOG87DD28
cp splitFasta.py EOG87DD29
cp splitFasta.py EOG87DD2H
cp splitFasta.py EOG87DD2K
cp splitFasta.py EOG87DD2N
cp splitFasta.py EOG87DD2P
cp splitFasta.py EOG87DD2S
cp splitFasta.py EOG87DD30
cp splitFasta.py EOG87DD36
cp splitFasta.py EOG87H896
cp splitFasta.py EOG87H897
cp splitFasta.py EOG87H89B
cp splitFasta.py EOG87H89D
cp splitFasta.py EOG87H89G
cp splitFasta.py EOG87H89K
cp splitFasta.py EOG87H89W
cp splitFasta.py EOG87M4J1
cp splitFasta.py EOG87M4J3
cp splitFasta.py EOG87M4J9
cp splitFasta.py EOG87M4JB
cp splitFasta.py EOG87M4JP
cp splitFasta.py EOG87M4JW
cp splitFasta.py EOG87Q0S4
cp splitFasta.py EOG87Q0S6
cp splitFasta.py EOG87Q0SW
cp splitFasta.py EOG87SW19
cp splitFasta.py EOG87SW1N
cp splitFasta.py EOG87WR7W
cp splitFasta.py EOG87WR81
cp splitFasta.py EOG87WR82
cp splitFasta.py EOG87WR85
cp splitFasta.py EOG880MGZ
cp splitFasta.py EOG880MH0
cp splitFasta.py EOG880MH6
cp splitFasta.py EOG880MH7
cp splitFasta.py EOG880MHB
cp splitFasta.py EOG880MHF
cp splitFasta.py EOG883GQT
cp splitFasta.py EOG883GQZ
cp splitFasta.py EOG883GR0
cp splitFasta.py EOG883GR2
cp splitFasta.py EOG883GR5
cp splitFasta.py EOG886BZQ
cp splitFasta.py EOG886BZR
cp splitFasta.py EOG886BZT
cp splitFasta.py EOG886BZV
cp splitFasta.py EOG886BZX
cp splitFasta.py EOG886BZZ
cp splitFasta.py EOG886C01
cp splitFasta.py EOG886C02
cp splitFasta.py EOG88976S
cp splitFasta.py EOG88976X
cp splitFasta.py EOG88976Z
cp splitFasta.py EOG889770
cp splitFasta.py EOG889775
cp splitFasta.py EOG88977B
cp splitFasta.py EOG88977C
cp splitFasta.py EOG88D3FJ
cp splitFasta.py EOG88D3FQ
cp splitFasta.py EOG88D3FR
cp splitFasta.py EOG88D3FV
cp splitFasta.py EOG88GZPK
cp splitFasta.py EOG88GZPN
cp splitFasta.py EOG88GZPS
cp splitFasta.py EOG88GZQ7
cp splitFasta.py EOG88GZQC
cp splitFasta.py EOG88KTX9
cp splitFasta.py EOG88KTXD
cp splitFasta.py EOG88KTXH
cp splitFasta.py EOG88KTXM
cp splitFasta.py EOG88KTXN
cp splitFasta.py EOG88KTXT
cp splitFasta.py EOG88PQ5B
cp splitFasta.py EOG88PQ5K
cp splitFasta.py EOG88PQ5M
cp splitFasta.py EOG88PQ5P
cp splitFasta.py EOG88PQ5X
cp splitFasta.py EOG88SKD7
cp splitFasta.py EOG88SKDB
cp splitFasta.py EOG88SKDC
cp splitFasta.py EOG88SKDH
cp splitFasta.py EOG88SKDM
cp splitFasta.py EOG88SKDP
cp splitFasta.py EOG88SKDR
cp splitFasta.py EOG88WFNG
cp splitFasta.py EOG88WFNH
cp splitFasta.py EOG88WFNK
cp splitFasta.py EOG88WFNP
cp splitFasta.py EOG88WFNS
cp splitFasta.py EOG88WFNV
cp splitFasta.py EOG88WFNX
cp splitFasta.py EOG8909W5
cp splitFasta.py EOG8909W7
cp splitFasta.py EOG8909W8
cp splitFasta.py EOG8909WB
cp splitFasta.py EOG8909WF
cp splitFasta.py EOG8909WG
cp splitFasta.py EOG8909WJ
cp splitFasta.py EOG8909WM
cp splitFasta.py EOG8909WS
cp splitFasta.py EOG893642
cp splitFasta.py EOG893644
cp splitFasta.py EOG893646
cp splitFasta.py EOG89364B
cp splitFasta.py EOG89364F
cp splitFasta.py EOG89364H
cp splitFasta.py EOG89364R
cp splitFasta.py EOG89364S
cp splitFasta.py EOG8962C2
cp splitFasta.py EOG8962C5
cp splitFasta.py EOG8962CC
cp splitFasta.py EOG8962CG
cp splitFasta.py EOG8962CM
cp splitFasta.py EOG8962CN
cp splitFasta.py EOG898XKZ
cp splitFasta.py EOG898XM0
cp splitFasta.py EOG898XM3
cp splitFasta.py EOG898XMC
cp splitFasta.py EOG898XMD
cp splitFasta.py EOG898XMN
cp splitFasta.py EOG898XMP
cp splitFasta.py EOG898XMQ
cp splitFasta.py EOG89CSTV
cp splitFasta.py EOG89CSTW
cp splitFasta.py EOG89CSV0
cp splitFasta.py EOG89CSV1
cp splitFasta.py EOG89CSV6
cp splitFasta.py EOG89CSV7
cp splitFasta.py EOG89CSV9
cp splitFasta.py EOG89CSVB
cp splitFasta.py EOG89CSVF
cp splitFasta.py EOG89CSVJ
cp splitFasta.py EOG89GP2Q
cp splitFasta.py EOG89GP2S
cp splitFasta.py EOG89GP2T
cp splitFasta.py EOG89GP2V
cp splitFasta.py EOG89GP2W
cp splitFasta.py EOG89GP2X
cp splitFasta.py EOG89GP30
cp splitFasta.py EOG89GP35
cp splitFasta.py EOG89GP36
cp splitFasta.py EOG89GP37
cp splitFasta.py EOG89GP3C
cp splitFasta.py EOG89GP3G
cp splitFasta.py EOG89GP3K
cp splitFasta.py EOG89KJ9R
cp splitFasta.py EOG89KJ9S
cp splitFasta.py EOG89KJ9V
cp splitFasta.py EOG89KJ9W
cp splitFasta.py EOG89KJB6
cp splitFasta.py EOG89KJB8
cp splitFasta.py EOG89KJBC
cp splitFasta.py EOG89KJBG
cp splitFasta.py EOG89PDJM
cp splitFasta.py EOG89PDJR
cp splitFasta.py EOG89PDK2
cp splitFasta.py EOG89PDK5
cp splitFasta.py EOG89PDK6
cp splitFasta.py EOG89S8SH
cp splitFasta.py EOG89S8SJ
cp splitFasta.py EOG89S8SK
cp splitFasta.py EOG89S8SN
cp splitFasta.py EOG89S8SP
cp splitFasta.py EOG89S8SR
cp splitFasta.py EOG89S8SS
cp splitFasta.py EOG89S8ST
cp splitFasta.py EOG89S8SV
cp splitFasta.py EOG89S8SW
cp splitFasta.py EOG89S8T2
cp splitFasta.py EOG89W51R
cp splitFasta.py EOG89W51T
cp splitFasta.py EOG89W51W
cp splitFasta.py EOG8B018D
cp splitFasta.py EOG8B018F
cp splitFasta.py EOG8B018H
cp splitFasta.py EOG8B018J
cp splitFasta.py EOG8B018P
cp splitFasta.py EOG8B018Q
cp splitFasta.py EOG8B018S
cp splitFasta.py EOG8B018T
cp splitFasta.py EOG8B018X
cp splitFasta.py EOG8B0192
cp splitFasta.py EOG8B0195
cp splitFasta.py EOG8B2WHF
cp splitFasta.py EOG8B2WHJ
cp splitFasta.py EOG8B2WHK
cp splitFasta.py EOG8B2WHQ
cp splitFasta.py EOG8B2WHS
cp splitFasta.py EOG8B2WHW
cp splitFasta.py EOG8B2WHX
cp splitFasta.py EOG8B2WHZ
cp splitFasta.py EOG8B2WJ3
cp splitFasta.py EOG8B2WJ6
cp splitFasta.py EOG8B5RRK
cp splitFasta.py EOG8B5RRQ
cp splitFasta.py EOG8B8N0C
cp splitFasta.py EOG8B8N0H
cp splitFasta.py EOG8B8N0N
cp splitFasta.py EOG8B8N0X
cp splitFasta.py EOG8BCH72
cp splitFasta.py EOG8BCH73
cp splitFasta.py EOG8BCH74
cp splitFasta.py EOG8BCH7B
cp splitFasta.py EOG8BCH7G
cp splitFasta.py EOG8BGCG2
cp splitFasta.py EOG8BGCGD
cp splitFasta.py EOG8BGCGP
cp splitFasta.py EOG8BGCGT
cp splitFasta.py EOG8BGCGX
cp splitFasta.py EOG8BK7Q4
cp splitFasta.py EOG8BK7Q6
cp splitFasta.py EOG8BK7Q9
cp splitFasta.py EOG8BK7QB
cp splitFasta.py EOG8BK7QH
cp splitFasta.py EOG8BK7QJ
cp splitFasta.py EOG8BP3XX
cp splitFasta.py EOG8BP3XZ
cp splitFasta.py EOG8BP3Z2
cp splitFasta.py EOG8BP3Z3
cp splitFasta.py EOG8BP3Z9
cp splitFasta.py EOG8BP3ZD
cp splitFasta.py EOG8BP3ZF
cp splitFasta.py EOG8BP3ZN
cp splitFasta.py EOG8BS05W
cp splitFasta.py EOG8BS05Z
cp splitFasta.py EOG8BS060
cp splitFasta.py EOG8BS064
cp splitFasta.py EOG8BS067
cp splitFasta.py EOG8BS068
cp splitFasta.py EOG8BS06B
cp splitFasta.py EOG8BS06J
cp splitFasta.py EOG8BS06Q
cp splitFasta.py EOG8BVVDW
cp splitFasta.py EOG8BVVDZ
cp splitFasta.py EOG8BVVF0
cp splitFasta.py EOG8BVVF3
cp splitFasta.py EOG8BVVFB
cp splitFasta.py EOG8BVVFD
cp splitFasta.py EOG8BZQNS
cp splitFasta.py EOG8BZQP2
cp splitFasta.py EOG8BZQP3
cp splitFasta.py EOG8BZQP4
cp splitFasta.py EOG8C2KWS
cp splitFasta.py EOG8C2KWT
cp splitFasta.py EOG8C2KWW
cp splitFasta.py EOG8C2KWX
cp splitFasta.py EOG8C2KWZ
cp splitFasta.py EOG8C2KX7
cp splitFasta.py EOG8C2KXB
cp splitFasta.py EOG8C2KXF
cp splitFasta.py EOG8C5G4M
cp splitFasta.py EOG8C5G4S
cp splitFasta.py EOG8C5G4T
cp splitFasta.py EOG8C5G4Z
cp splitFasta.py EOG8C5G57
cp splitFasta.py EOG8C8BCJ
cp splitFasta.py EOG8C8BCM
cp splitFasta.py EOG8C8BCP
cp splitFasta.py EOG8C8BCV
cp splitFasta.py EOG8C8BCX
cp splitFasta.py EOG8C8BD1
cp splitFasta.py EOG8C8BD6
cp splitFasta.py EOG8C8BD7
cp splitFasta.py EOG8CC6MJ
cp splitFasta.py EOG8CC6MK
cp splitFasta.py EOG8CC6MM
cp splitFasta.py EOG8CC6MP
cp splitFasta.py EOG8CC6MT
cp splitFasta.py EOG8CC6MV
cp splitFasta.py EOG8CC6N0
cp splitFasta.py EOG8CC6N7
cp splitFasta.py EOG8CG2VC
cp splitFasta.py EOG8CG2VF
cp splitFasta.py EOG8CG2VK
cp splitFasta.py EOG8CG2VQ
cp splitFasta.py EOG8CG2VZ
cp splitFasta.py EOG8CG2W1
cp splitFasta.py EOG8CJZ38
cp splitFasta.py EOG8CJZ3B
cp splitFasta.py EOG8CJZ3J
cp splitFasta.py EOG8CJZ3K
cp splitFasta.py EOG8CJZ3M
cp splitFasta.py EOG8CJZ3W
cp splitFasta.py EOG8CNTB7
cp splitFasta.py EOG8CNTBB
cp splitFasta.py EOG8CNTBD
cp splitFasta.py EOG8CNTBF
cp splitFasta.py EOG8CNTBG
cp splitFasta.py EOG8CNTBN
cp splitFasta.py EOG8CNTC3
cp splitFasta.py EOG8CRPK5
cp splitFasta.py EOG8CRPK8
cp splitFasta.py EOG8CRPKB
cp splitFasta.py EOG8CRPKD
cp splitFasta.py EOG8CRPKF
cp splitFasta.py EOG8CRPKH
cp splitFasta.py EOG8CRPKM
cp splitFasta.py EOG8CRPKQ
cp splitFasta.py EOG8CVJT5
cp splitFasta.py EOG8CVJT9
cp splitFasta.py EOG8CVJTC
cp splitFasta.py EOG8CVJTG
cp splitFasta.py EOG8CVJTJ
cp splitFasta.py EOG8CVJTK
cp splitFasta.py EOG8CVJTM
cp splitFasta.py EOG8CVJTW
cp splitFasta.py EOG8CZF21
cp splitFasta.py EOG8CZF24
cp splitFasta.py EOG8CZF26
cp splitFasta.py EOG8CZF27
cp splitFasta.py EOG8CZF2J
cp splitFasta.py EOG8D2993
cp splitFasta.py EOG8D2995
cp splitFasta.py EOG8D2997
cp splitFasta.py EOG8D299B
cp splitFasta.py EOG8D299D
cp splitFasta.py EOG8D299K
cp splitFasta.py EOG8D299S
cp splitFasta.py EOG8D55HW
cp splitFasta.py EOG8D55HZ
cp splitFasta.py EOG8D55J3
cp splitFasta.py EOG8D55J4
cp splitFasta.py EOG8D55J6
cp splitFasta.py EOG8D55JH
cp splitFasta.py EOG8D55JM
cp splitFasta.py EOG8D55JP
cp splitFasta.py EOG8D81RT
cp splitFasta.py EOG8D81RX
cp splitFasta.py EOG8D81S1
cp splitFasta.py EOG8D81S5
cp splitFasta.py EOG8D81SD
cp splitFasta.py EOG8D81SR
cp splitFasta.py EOG8DBX0S
cp splitFasta.py EOG8DBX0V
cp splitFasta.py EOG8DBX0W
cp splitFasta.py EOG8DBX0X
cp splitFasta.py EOG8DBX12
cp splitFasta.py EOG8DBX13
cp splitFasta.py EOG8DBX14
cp splitFasta.py EOG8DBX15
cp splitFasta.py EOG8DBX16
cp splitFasta.py EOG8DBX18
cp splitFasta.py EOG8DBX19
cp splitFasta.py EOG8DBX1G
cp splitFasta.py EOG8DFS80
cp splitFasta.py EOG8DFS84
cp splitFasta.py EOG8DFS85
cp splitFasta.py EOG8DFS86
cp splitFasta.py EOG8DJNGK
cp splitFasta.py EOG8DJNGM
cp splitFasta.py EOG8DJNGP
cp splitFasta.py EOG8DJNGQ
cp splitFasta.py EOG8DJNGW
cp splitFasta.py EOG8DJNH5
cp splitFasta.py EOG8DNHQH
cp splitFasta.py EOG8DNHQK
cp splitFasta.py EOG8DNHQM
cp splitFasta.py EOG8DNHQN
cp splitFasta.py EOG8DNHQP
cp splitFasta.py EOG8DNHQR
cp splitFasta.py EOG8DNHQS
cp splitFasta.py EOG8DNHQX
cp splitFasta.py EOG8DNHQZ
cp splitFasta.py EOG8DRCZJ
cp splitFasta.py EOG8DRCZM
cp splitFasta.py EOG8DRCZN
cp splitFasta.py EOG8DRCZR
cp splitFasta.py EOG8DRCZT
cp splitFasta.py EOG8DRCZV
cp splitFasta.py EOG8DRCZW
cp splitFasta.py EOG8DRCZZ
cp splitFasta.py EOG8DRD01
cp splitFasta.py EOG8DRD02
cp splitFasta.py EOG8DRD06
cp splitFasta.py EOG8DV86F
cp splitFasta.py EOG8DV86H
cp splitFasta.py EOG8DV86M
cp splitFasta.py EOG8DV86N
cp splitFasta.py EOG8DV873
cp splitFasta.py EOG8DV874
cp splitFasta.py EOG8DV877
cp splitFasta.py EOG8DZ4FM
cp splitFasta.py EOG8DZ4FN
cp splitFasta.py EOG8DZ4FP
cp splitFasta.py EOG8DZ4G1
cp splitFasta.py EOG8F20PB
cp splitFasta.py EOG8F20PC
cp splitFasta.py EOG8F20PF
cp splitFasta.py EOG8F20PG
cp splitFasta.py EOG8F20PQ
cp splitFasta.py EOG8F20PS
cp splitFasta.py EOG8F20PZ
cp splitFasta.py EOG8F20Q0
cp splitFasta.py EOG8F20Q3
cp splitFasta.py EOG8F20Q5
cp splitFasta.py EOG8F4VX5
cp splitFasta.py EOG8F4VX8
cp splitFasta.py EOG8F4VXB
cp splitFasta.py EOG8F4VXD
cp splitFasta.py EOG8F4VXG
cp splitFasta.py EOG8F4VXK
cp splitFasta.py EOG8F4VXM
cp splitFasta.py EOG8F4VXR
cp splitFasta.py EOG8F7R55
cp splitFasta.py EOG8F7R57
cp splitFasta.py EOG8F7R58
cp splitFasta.py EOG8F7R5F
cp splitFasta.py EOG8F7R5P
cp splitFasta.py EOG8F7R5S
cp splitFasta.py EOG8FBMD2
cp splitFasta.py EOG8FBMDB
cp splitFasta.py EOG8FBMDC
cp splitFasta.py EOG8FBMDF
cp splitFasta.py EOG8FBMDM
cp splitFasta.py EOG8FBMDQ
cp splitFasta.py EOG8FFGN1
cp splitFasta.py EOG8FFGN5
cp splitFasta.py EOG8FFGN7
cp splitFasta.py EOG8FFGN8
cp splitFasta.py EOG8FFGNM
cp splitFasta.py EOG8FFGNQ
cp splitFasta.py EOG8FJBVW
cp splitFasta.py EOG8FJBW0
cp splitFasta.py EOG8FJBW2
cp splitFasta.py EOG8FJBW8
cp splitFasta.py EOG8FJBW9
cp splitFasta.py EOG8FJBWD
cp splitFasta.py EOG8FJBWH
cp splitFasta.py EOG8FJBWQ
cp splitFasta.py EOG8FJBWV
cp splitFasta.py EOG8FN740
cp splitFasta.py EOG8FN742
cp splitFasta.py EOG8FN745
cp splitFasta.py EOG8FN74J
cp splitFasta.py EOG8FN74Q
cp splitFasta.py EOG8FR3BS
cp splitFasta.py EOG8FR3BW
cp splitFasta.py EOG8FR3C1
cp splitFasta.py EOG8FR3CC
cp splitFasta.py EOG8FTZKP
cp splitFasta.py EOG8FTZKQ
cp splitFasta.py EOG8FTZKT
cp splitFasta.py EOG8FTZM5
cp splitFasta.py EOG8FTZM6
cp splitFasta.py EOG8FXTTW
cp splitFasta.py EOG8FXTV2
cp splitFasta.py EOG8FXTV6
cp splitFasta.py EOG8FXTVC
cp splitFasta.py EOG8FXTVD
cp splitFasta.py EOG8FXTVM
cp splitFasta.py EOG8G1Q2J
cp splitFasta.py EOG8G1Q2P
cp splitFasta.py EOG8G1Q2R
cp splitFasta.py EOG8G1Q2T
cp splitFasta.py EOG8G1Q2V
cp splitFasta.py EOG8G1Q2W
cp splitFasta.py EOG8G1Q2X
cp splitFasta.py EOG8G1Q30
cp splitFasta.py EOG8G4K9M
cp splitFasta.py EOG8G4K9N
cp splitFasta.py EOG8G4K9P
cp splitFasta.py EOG8G4K9S
cp splitFasta.py EOG8G4K9V
cp splitFasta.py EOG8G7FJQ
cp splitFasta.py EOG8G7FJR
cp splitFasta.py EOG8G7FK6
cp splitFasta.py EOG8G7FKD
cp splitFasta.py EOG8GB9SB
cp splitFasta.py EOG8GB9SK
cp splitFasta.py EOG8GB9SR
cp splitFasta.py EOG8GB9ST
cp splitFasta.py EOG8GB9T1
cp splitFasta.py EOG8GF617
cp splitFasta.py EOG8GF618
cp splitFasta.py EOG8GF61B
cp splitFasta.py EOG8GF61D
cp splitFasta.py EOG8GF61H
cp splitFasta.py EOG8GF61K
cp splitFasta.py EOG8GF61R
cp splitFasta.py EOG8GF621
cp splitFasta.py EOG8GJ28D
cp splitFasta.py EOG8GJ28F
cp splitFasta.py EOG8GJ28H
cp splitFasta.py EOG8GJ28J
cp splitFasta.py EOG8GJ28R
cp splitFasta.py EOG8GJ28V
cp splitFasta.py EOG8GJ294
cp splitFasta.py EOG8GMXH4
cp splitFasta.py EOG8GMXH5
cp splitFasta.py EOG8GMXH7
cp splitFasta.py EOG8GMXH8
cp splitFasta.py EOG8GMXHB
cp splitFasta.py EOG8GMXHD
cp splitFasta.py EOG8GMXHJ
cp splitFasta.py EOG8GMXHK
cp splitFasta.py EOG8GMXHT
cp splitFasta.py EOG8GQSR3
cp splitFasta.py EOG8GQSR8
cp splitFasta.py EOG8GQSRB
cp splitFasta.py EOG8GQSRF
cp splitFasta.py EOG8GQSRJ
cp splitFasta.py EOG8GQSRK
cp splitFasta.py EOG8GQSRX
cp splitFasta.py EOG8GTP05
cp splitFasta.py EOG8GTP08
cp splitFasta.py EOG8GTP0D
cp splitFasta.py EOG8GTP0J
cp splitFasta.py EOG8GXJ70
cp splitFasta.py EOG8GXJ71
cp splitFasta.py EOG8GXJ72
cp splitFasta.py EOG8GXJ73
cp splitFasta.py EOG8GXJ7D
cp splitFasta.py EOG8GXJ7N
cp splitFasta.py EOG8H1DFX
cp splitFasta.py EOG8H1DFZ
cp splitFasta.py EOG8H1DG0
cp splitFasta.py EOG8H1DG1
cp splitFasta.py EOG8H1DG4
cp splitFasta.py EOG8H1DG6
cp splitFasta.py EOG8H1DGH
cp splitFasta.py EOG8H1DGK
cp splitFasta.py EOG8H1DGV
cp splitFasta.py EOG8H48PW
cp splitFasta.py EOG8H48Q0
cp splitFasta.py EOG8H48Q1
cp splitFasta.py EOG8H48Q4
cp splitFasta.py EOG8H48Q5
cp splitFasta.py EOG8H48QR
cp splitFasta.py EOG8H74XT
cp splitFasta.py EOG8H74XX
cp splitFasta.py EOG8H74XZ
cp splitFasta.py EOG8H74Z2
cp splitFasta.py EOG8H74Z3
cp splitFasta.py EOG8H74Z4
cp splitFasta.py EOG8H74Z5
cp splitFasta.py EOG8H74Z6
cp splitFasta.py EOG8HB15M
cp splitFasta.py EOG8HB15P
cp splitFasta.py EOG8HB15Q
cp splitFasta.py EOG8HB15R
cp splitFasta.py EOG8HB15T
cp splitFasta.py EOG8HB15V
cp splitFasta.py EOG8HB160
cp splitFasta.py EOG8HB166
cp splitFasta.py EOG8HB167
cp splitFasta.py EOG8HB16C
cp splitFasta.py EOG8HB16G
cp splitFasta.py EOG8HDWDQ
cp splitFasta.py EOG8HDWDS
cp splitFasta.py EOG8HDWDW
cp splitFasta.py EOG8HDWDZ
cp splitFasta.py EOG8HDWF0
cp splitFasta.py EOG8HDWF8
cp splitFasta.py EOG8HHRNJ
cp splitFasta.py EOG8HHRNP
cp splitFasta.py EOG8HHRNS
cp splitFasta.py EOG8HHRNV
cp splitFasta.py EOG8HHRNW
cp splitFasta.py EOG8HHRNZ
cp splitFasta.py EOG8HHRP8
cp splitFasta.py EOG8HMMWC
cp splitFasta.py EOG8HMMWD
cp splitFasta.py EOG8HMMWG
cp splitFasta.py EOG8HMMWH
cp splitFasta.py EOG8HMMWM
cp splitFasta.py EOG8HMMWR
cp splitFasta.py EOG8HMMWT
cp splitFasta.py EOG8HMMWV
cp splitFasta.py EOG8HMMWX
cp splitFasta.py EOG8HQH4G
cp splitFasta.py EOG8HQH4K
cp splitFasta.py EOG8HQH4S
cp splitFasta.py EOG8HQH4Z
cp splitFasta.py EOG8HQH55
cp splitFasta.py EOG8HTCCD
cp splitFasta.py EOG8HTCCF
cp splitFasta.py EOG8HTCCJ
cp splitFasta.py EOG8HTCCQ
cp splitFasta.py EOG8HTCD4
cp splitFasta.py EOG8HX7M8
cp splitFasta.py EOG8HX7M9
cp splitFasta.py EOG8HX7MB
cp splitFasta.py EOG8HX7MD
cp splitFasta.py EOG8HX7MF
cp splitFasta.py EOG8HX7MH
cp splitFasta.py EOG8HX7MK
cp splitFasta.py EOG8HX7MM
cp splitFasta.py EOG8HX7MN
cp splitFasta.py EOG8HX7N2
cp splitFasta.py EOG8J13V6
cp splitFasta.py EOG8J13V7
cp splitFasta.py EOG8J13VD
cp splitFasta.py EOG8J13VF
cp splitFasta.py EOG8J13VJ
cp splitFasta.py EOG8J13VK
cp splitFasta.py EOG8J13VR
cp splitFasta.py EOG8J13VT
cp splitFasta.py EOG8J13VX
cp splitFasta.py EOG8J13VZ
cp splitFasta.py EOG8J4036
cp splitFasta.py EOG8J4039
cp splitFasta.py EOG8J403C
cp splitFasta.py EOG8J6VB1
cp splitFasta.py EOG8J6VB4
cp splitFasta.py EOG8J6VB6
cp splitFasta.py EOG8J6VB7
cp splitFasta.py EOG8J6VBF
cp splitFasta.py EOG8J6VBK
cp splitFasta.py EOG8J6VBZ
cp splitFasta.py EOG8J9QK1
cp splitFasta.py EOG8J9QK2
cp splitFasta.py EOG8J9QK3
cp splitFasta.py EOG8J9QK7
cp splitFasta.py EOG8J9QKD
cp splitFasta.py EOG8J9QKF
cp splitFasta.py EOG8J9QKV
cp splitFasta.py EOG8JDKT2
cp splitFasta.py EOG8JDKT4
cp splitFasta.py EOG8JDKT7
cp splitFasta.py EOG8JDKT9
cp splitFasta.py EOG8JDKTC
cp splitFasta.py EOG8JDKTD
cp splitFasta.py EOG8JDKTJ
cp splitFasta.py EOG8JHG22
cp splitFasta.py EOG8JHG24
cp splitFasta.py EOG8JHG25
cp splitFasta.py EOG8JHG2C
cp splitFasta.py EOG8JMB8V
cp splitFasta.py EOG8JMB8X
cp splitFasta.py EOG8JMB93
cp splitFasta.py EOG8JMB9G
cp splitFasta.py EOG8JMB9P
cp splitFasta.py EOG8JQ6HS
cp splitFasta.py EOG8JQ6HT
cp splitFasta.py EOG8JQ6HV
cp splitFasta.py EOG8JQ6J0
cp splitFasta.py EOG8JQ6J8
cp splitFasta.py EOG8JQ6J9
cp splitFasta.py EOG8JQ6JD
cp splitFasta.py EOG8JQ6JJ
cp splitFasta.py EOG8JT2RP
cp splitFasta.py EOG8JT2RS
cp splitFasta.py EOG8JT2RZ
cp splitFasta.py EOG8JT2S0
cp splitFasta.py EOG8JT2S5
cp splitFasta.py EOG8JT2SB
cp splitFasta.py EOG8JT2SK
cp splitFasta.py EOG8JWZ0K
cp splitFasta.py EOG8JWZ0M
cp splitFasta.py EOG8JWZ0T
cp splitFasta.py EOG8JWZ0W
cp splitFasta.py EOG8JWZ0X
cp splitFasta.py EOG8JWZ10
cp splitFasta.py EOG8K0T7P
cp splitFasta.py EOG8K0T7S
cp splitFasta.py EOG8K0T7W
cp splitFasta.py EOG8K0T7X
cp splitFasta.py EOG8K0T7Z
cp splitFasta.py EOG8K0T86
cp splitFasta.py EOG8K3PGH
cp splitFasta.py EOG8K3PGJ
cp splitFasta.py EOG8K3PGV
cp splitFasta.py EOG8K3PGX
cp splitFasta.py EOG8K3PH4
cp splitFasta.py EOG8K3PH7
cp splitFasta.py EOG8K6JQB
cp splitFasta.py EOG8K6JQF
cp splitFasta.py EOG8K6JQJ
cp splitFasta.py EOG8K6JQM
cp splitFasta.py EOG8K6JQQ
cp splitFasta.py EOG8K6JR5
cp splitFasta.py EOG8K9DZ9
cp splitFasta.py EOG8K9DZB
cp splitFasta.py EOG8K9DZD
cp splitFasta.py EOG8K9DZG
cp splitFasta.py EOG8K9DZM
cp splitFasta.py EOG8K9DZS
cp splitFasta.py EOG8K9DZT
cp splitFasta.py EOG8K9F01
cp splitFasta.py EOG8KD966
cp splitFasta.py EOG8KD968
cp splitFasta.py EOG8KD96C
cp splitFasta.py EOG8KD96D
cp splitFasta.py EOG8KD96M
cp splitFasta.py EOG8KD96Q
cp splitFasta.py EOG8KH5F3
cp splitFasta.py EOG8KH5F5
cp splitFasta.py EOG8KH5F7
cp splitFasta.py EOG8KH5F9
cp splitFasta.py EOG8KH5FG
cp splitFasta.py EOG8KH5FV
cp splitFasta.py EOG8KH5FZ
cp splitFasta.py EOG8KM1P7
cp splitFasta.py EOG8KM1P8
cp splitFasta.py EOG8KM1PB
cp splitFasta.py EOG8KM1PD
cp splitFasta.py EOG8KM1PM
cp splitFasta.py EOG8KM1PW
cp splitFasta.py EOG8KPWX2
cp splitFasta.py EOG8KPWX3
cp splitFasta.py EOG8KPWX7
cp splitFasta.py EOG8KPWX8
cp splitFasta.py EOG8KPWXB
cp splitFasta.py EOG8KPWXD
cp splitFasta.py EOG8KPWXW
cp splitFasta.py EOG8KSS4W
cp splitFasta.py EOG8KSS4X
cp splitFasta.py EOG8KSS50
cp splitFasta.py EOG8KSS53
cp splitFasta.py EOG8KSS59
cp splitFasta.py EOG8KSS5P
cp splitFasta.py EOG8KWNCX
cp splitFasta.py EOG8KWND0
cp splitFasta.py EOG8KWND4
cp splitFasta.py EOG8KWND7
cp splitFasta.py EOG8KWND9
cp splitFasta.py EOG8KWNDF
cp splitFasta.py EOG8M0HMZ
cp splitFasta.py EOG8M0HN0
cp splitFasta.py EOG8M0HN2
cp splitFasta.py EOG8M0HN3
cp splitFasta.py EOG8M0HN9
cp splitFasta.py EOG8M0HNC
cp splitFasta.py EOG8M0HNF
cp splitFasta.py EOG8M0HNJ
cp splitFasta.py EOG8M0HNQ
cp splitFasta.py EOG8M3CVR
cp splitFasta.py EOG8M3CVV
cp splitFasta.py EOG8M3CVW
cp splitFasta.py EOG8M3CVZ
cp splitFasta.py EOG8M3CW0
cp splitFasta.py EOG8M3CWF
cp splitFasta.py EOG8M3CWJ
cp splitFasta.py EOG8M3CWN
cp splitFasta.py EOG8M683T
cp splitFasta.py EOG8M683Z
cp splitFasta.py EOG8M6840
cp splitFasta.py EOG8M6843
cp splitFasta.py EOG8M6849
cp splitFasta.py EOG8M684C
cp splitFasta.py EOG8M684G
cp splitFasta.py EOG8M94BN
cp splitFasta.py EOG8M94BQ
cp splitFasta.py EOG8M94BX
cp splitFasta.py EOG8M94C1
cp splitFasta.py EOG8M94C2
cp splitFasta.py EOG8M94C6
cp splitFasta.py EOG8MD0KG
cp splitFasta.py EOG8MD0KP
cp splitFasta.py EOG8MD0KW
cp splitFasta.py EOG8MD0KX
cp splitFasta.py EOG8MD0M3
cp splitFasta.py EOG8MGVTJ
cp splitFasta.py EOG8MGVTK
cp splitFasta.py EOG8MGVTM
cp splitFasta.py EOG8MGVTN
cp splitFasta.py EOG8MGVTR
cp splitFasta.py EOG8MGVTT
cp splitFasta.py EOG8MGVTW
cp splitFasta.py EOG8MGVTZ
cp splitFasta.py EOG8MGVV0
cp splitFasta.py EOG8MGVV6
cp splitFasta.py EOG8MGVV9
cp splitFasta.py EOG8MGVVD
cp splitFasta.py EOG8MKR2M
cp splitFasta.py EOG8MKR2N
cp splitFasta.py EOG8MKR2R
cp splitFasta.py EOG8MKR2V
cp splitFasta.py EOG8MPM9B
cp splitFasta.py EOG8MPM9C
cp splitFasta.py EOG8MPM9F
cp splitFasta.py EOG8MPM9G
cp splitFasta.py EOG8MPM9J
cp splitFasta.py EOG8MPM9N
cp splitFasta.py EOG8MPM9T
cp splitFasta.py EOG8MPM9V
cp splitFasta.py EOG8MPMB2
cp splitFasta.py EOG8MSGJ8
cp splitFasta.py EOG8MSGJ9
cp splitFasta.py EOG8MSGJJ
cp splitFasta.py EOG8MSGJP
cp splitFasta.py EOG8MSGJW
cp splitFasta.py EOG8MWBSK
cp splitFasta.py EOG8MWBSM
cp splitFasta.py EOG8MWBSQ
cp splitFasta.py EOG8MWBSS
cp splitFasta.py EOG8MWBSV
cp splitFasta.py EOG8MWBSW
cp splitFasta.py EOG8N0713
cp splitFasta.py EOG8N0715
cp splitFasta.py EOG8N0718
cp splitFasta.py EOG8N071H
cp splitFasta.py EOG8N071M
cp splitFasta.py EOG8N3380
cp splitFasta.py EOG8N3384
cp splitFasta.py EOG8N3388
cp splitFasta.py EOG8N338G
cp splitFasta.py EOG8N338Q
cp splitFasta.py EOG8N338R
cp splitFasta.py EOG8N5ZH1
cp splitFasta.py EOG8N5ZH4
cp splitFasta.py EOG8N5ZH6
cp splitFasta.py EOG8N5ZHD
cp splitFasta.py EOG8N5ZHH
cp splitFasta.py EOG8N8TQW
cp splitFasta.py EOG8N8TQX
cp splitFasta.py EOG8N8TR3
cp splitFasta.py EOG8N8TR7
cp splitFasta.py EOG8N8TR8
cp splitFasta.py EOG8N8TR9
cp splitFasta.py EOG8N8TRD
cp splitFasta.py EOG8N8TRF
cp splitFasta.py EOG8N8TRR
cp splitFasta.py EOG8NCQ00
cp splitFasta.py EOG8NCQ04
cp splitFasta.py EOG8NCQ05
cp splitFasta.py EOG8NCQ0B
cp splitFasta.py EOG8NCQ0H
cp splitFasta.py EOG8NCQ0P
cp splitFasta.py EOG8NGK6Z
cp splitFasta.py EOG8NGK72
cp splitFasta.py EOG8NGK73
cp splitFasta.py EOG8NGK79
cp splitFasta.py EOG8NGK7B
cp splitFasta.py EOG8NGK7C
cp splitFasta.py EOG8NGK7F
cp splitFasta.py EOG8NGK7R
cp splitFasta.py EOG8NKFFQ
cp splitFasta.py EOG8NKFFR
cp splitFasta.py EOG8NKFFS
cp splitFasta.py EOG8NKFG1
cp splitFasta.py EOG8NKFG2
cp splitFasta.py EOG8NKFG4
cp splitFasta.py EOG8NKFGK
cp splitFasta.py EOG8NP9PP
cp splitFasta.py EOG8NP9PR
cp splitFasta.py EOG8NP9Q4
cp splitFasta.py EOG8NS5XN
cp splitFasta.py EOG8NS5XQ
cp splitFasta.py EOG8NS5XS
cp splitFasta.py EOG8NS5XT
cp splitFasta.py EOG8NS5Z1
cp splitFasta.py EOG8NS5ZF
cp splitFasta.py EOG8NW25F
cp splitFasta.py EOG8NW25R
cp splitFasta.py EOG8NW260
cp splitFasta.py EOG8NW265
cp splitFasta.py EOG8NW267
cp splitFasta.py EOG8NZXDF
cp splitFasta.py EOG8NZXDJ
cp splitFasta.py EOG8NZXDV
cp splitFasta.py EOG8NZXF0
cp splitFasta.py EOG8P2SNC
cp splitFasta.py EOG8P2SNG
cp splitFasta.py EOG8P2SNJ
cp splitFasta.py EOG8P2SNK
cp splitFasta.py EOG8P2SNM
cp splitFasta.py EOG8P2SNP
cp splitFasta.py EOG8P2SNQ
cp splitFasta.py EOG8P2SNT
cp splitFasta.py EOG8P2SP8
cp splitFasta.py EOG8P5NW8
cp splitFasta.py EOG8P5NWB
cp splitFasta.py EOG8P5NWF
cp splitFasta.py EOG8P5NWJ
cp splitFasta.py EOG8P5NWK
cp splitFasta.py EOG8P5NWN
cp splitFasta.py EOG8P5NWP
cp splitFasta.py EOG8P5NWR
cp splitFasta.py EOG8P5NX0
cp splitFasta.py EOG8P8J46
cp splitFasta.py EOG8P8J47
cp splitFasta.py EOG8P8J48
cp splitFasta.py EOG8P8J4B
cp splitFasta.py EOG8P8J4D
cp splitFasta.py EOG8P8J4H
cp splitFasta.py EOG8P8J4M
cp splitFasta.py EOG8P8J4V
cp splitFasta.py EOG8P8J4X
cp splitFasta.py EOG8P8J51
cp splitFasta.py EOG8PCDCC
cp splitFasta.py EOG8PCDCH
cp splitFasta.py EOG8PCDCN
cp splitFasta.py EOG8PCDCR
cp splitFasta.py EOG8PCDD0
cp splitFasta.py EOG8PG8M4
cp splitFasta.py EOG8PG8MB
cp splitFasta.py EOG8PG8MJ
cp splitFasta.py EOG8PG8MK
cp splitFasta.py EOG8PK4V0
cp splitFasta.py EOG8PK4V1
cp splitFasta.py EOG8PK4V3
cp splitFasta.py EOG8PK4V5
cp splitFasta.py EOG8PK4V7
cp splitFasta.py EOG8PK4VB
cp splitFasta.py EOG8PK4VG
cp splitFasta.py EOG8PP131
cp splitFasta.py EOG8PP133
cp splitFasta.py EOG8PP134
cp splitFasta.py EOG8PP135
cp splitFasta.py EOG8PP137
cp splitFasta.py EOG8PP138
cp splitFasta.py EOG8PP13C
cp splitFasta.py EOG8PP13D
cp splitFasta.py EOG8PP13J
cp splitFasta.py EOG8PP13S
cp splitFasta.py EOG8PRWB0
cp splitFasta.py EOG8PRWB2
cp splitFasta.py EOG8PRWB4
cp splitFasta.py EOG8PRWB5
cp splitFasta.py EOG8PRWB7
cp splitFasta.py EOG8PRWB8
cp splitFasta.py EOG8PRWBD
cp splitFasta.py EOG8PRWBF
cp splitFasta.py EOG8PVRJS
cp splitFasta.py EOG8PVRJT
cp splitFasta.py EOG8PVRJV
cp splitFasta.py EOG8PVRK0
cp splitFasta.py EOG8PVRK5
cp splitFasta.py EOG8PVRKB
cp splitFasta.py EOG8PVRKD
cp splitFasta.py EOG8PVRKG
cp splitFasta.py EOG8PVRKN
cp splitFasta.py EOG8PZMSQ
cp splitFasta.py EOG8PZMSR
cp splitFasta.py EOG8PZMSS
cp splitFasta.py EOG8PZMSV
cp splitFasta.py EOG8PZMSZ
cp splitFasta.py EOG8PZMT4
cp splitFasta.py EOG8PZMT5
cp splitFasta.py EOG8PZMT7
cp splitFasta.py EOG8PZMT8
cp splitFasta.py EOG8PZMTN
cp splitFasta.py EOG8Q2H1R
cp splitFasta.py EOG8Q2H1T
cp splitFasta.py EOG8Q2H1X
cp splitFasta.py EOG8Q2H21
cp splitFasta.py EOG8Q2H22
cp splitFasta.py EOG8Q2H24
cp splitFasta.py EOG8Q5C8K
cp splitFasta.py EOG8Q5C8M
cp splitFasta.py EOG8Q5C8Q
cp splitFasta.py EOG8Q5C8R
cp splitFasta.py EOG8Q5C8S
cp splitFasta.py EOG8Q5C8V
cp splitFasta.py EOG8Q5C90
cp splitFasta.py EOG8Q5C93
cp splitFasta.py EOG8Q5C94
cp splitFasta.py EOG8Q5C96
cp splitFasta.py EOG8Q87HN
cp splitFasta.py EOG8Q87HP
cp splitFasta.py EOG8Q87HQ
cp splitFasta.py EOG8Q87HR
cp splitFasta.py EOG8Q87HT
cp splitFasta.py EOG8Q87HX
cp splitFasta.py EOG8Q87J5
cp splitFasta.py EOG8Q87J7
cp splitFasta.py EOG8Q87J8
cp splitFasta.py EOG8QC3RJ
cp splitFasta.py EOG8QC3RM
cp splitFasta.py EOG8QC3RR
cp splitFasta.py EOG8QC3RS
cp splitFasta.py EOG8QC3RT
cp splitFasta.py EOG8QC3RW
cp splitFasta.py EOG8QC3RZ
cp splitFasta.py EOG8QC3S9
cp splitFasta.py EOG8QG00R
cp splitFasta.py EOG8QG00S
cp splitFasta.py EOG8QG00V
cp splitFasta.py EOG8QG00W
cp splitFasta.py EOG8QG00X
cp splitFasta.py EOG8QG00Z
cp splitFasta.py EOG8QJV78
cp splitFasta.py EOG8QJV79
cp splitFasta.py EOG8QJV7B
cp splitFasta.py EOG8QJV7G
cp splitFasta.py EOG8QJV7H
cp splitFasta.py EOG8QJV7J
cp splitFasta.py EOG8QJV7Q
cp splitFasta.py EOG8QJV7R
cp splitFasta.py EOG8QJV7X
cp splitFasta.py EOG8QJV80
cp splitFasta.py EOG8QNQGD
cp splitFasta.py EOG8QNQGS
cp splitFasta.py EOG8QNQGT
cp splitFasta.py EOG8QNQGV
cp splitFasta.py EOG8QRKQ9
cp splitFasta.py EOG8QRKQJ
cp splitFasta.py EOG8QRKQN
cp splitFasta.py EOG8QRKQP
cp splitFasta.py EOG8QRKQX
cp splitFasta.py EOG8QVFZ3
cp splitFasta.py EOG8QVFZ5
cp splitFasta.py EOG8QVFZ8
cp splitFasta.py EOG8QVFZ9
cp splitFasta.py EOG8QVFZB
cp splitFasta.py EOG8QVFZF
cp splitFasta.py EOG8QVFZH
cp splitFasta.py EOG8QVFZK
cp splitFasta.py EOG8QVFZM
cp splitFasta.py EOG8QVFZV
cp splitFasta.py EOG8QZB62
cp splitFasta.py EOG8QZB63
cp splitFasta.py EOG8QZB65
cp splitFasta.py EOG8QZB66
cp splitFasta.py EOG8QZB6F
cp splitFasta.py EOG8QZB6G
cp splitFasta.py EOG8QZB6P
cp splitFasta.py EOG8QZB6Q
cp splitFasta.py EOG8R26DZ
cp splitFasta.py EOG8R26F2
cp splitFasta.py EOG8R26F5
cp splitFasta.py EOG8R26F6
cp splitFasta.py EOG8R26FB
cp splitFasta.py EOG8R26FG
cp splitFasta.py EOG8R26FH
cp splitFasta.py EOG8R52P2
cp splitFasta.py EOG8R52PC
cp splitFasta.py EOG8R52PJ
cp splitFasta.py EOG8R7XWW
cp splitFasta.py EOG8R7XWX
cp splitFasta.py EOG8R7XX2
cp splitFasta.py EOG8R7XX4
cp splitFasta.py EOG8R7XX5
cp splitFasta.py EOG8R7XX6
cp splitFasta.py EOG8R7XX9
cp splitFasta.py EOG8R7XXH
cp splitFasta.py EOG8RBT4V
cp splitFasta.py EOG8RBT4X
cp splitFasta.py EOG8RBT50
cp splitFasta.py EOG8RBT5B
cp splitFasta.py EOG8RFPCV
cp splitFasta.py EOG8RFPD4
cp splitFasta.py EOG8RFPD8
cp splitFasta.py EOG8RFPDF
cp splitFasta.py EOG8RFPDG
cp splitFasta.py EOG8RFPDM
cp splitFasta.py EOG8RJJMS
cp splitFasta.py EOG8RJJMW
cp splitFasta.py EOG8RJJN2
cp splitFasta.py EOG8RJJN4
cp splitFasta.py EOG8RJJN6
cp splitFasta.py EOG8RJJN7
cp splitFasta.py EOG8RJJNH
cp splitFasta.py EOG8RNDVM
cp splitFasta.py EOG8RNDVN
cp splitFasta.py EOG8RNDVP
cp splitFasta.py EOG8RNDVR
cp splitFasta.py EOG8RNDVS
cp splitFasta.py EOG8RNDVV
cp splitFasta.py EOG8RNDVW
cp splitFasta.py EOG8RNDVZ
cp splitFasta.py EOG8RNDW0
cp splitFasta.py EOG8RNDW2
cp splitFasta.py EOG8RNDW3
cp splitFasta.py EOG8RNDW4
cp splitFasta.py EOG8RNDW5
cp splitFasta.py EOG8RNDW9
cp splitFasta.py EOG8RNDWB
cp splitFasta.py EOG8RNDWJ
cp splitFasta.py EOG8RR93F
cp splitFasta.py EOG8RR93H
cp splitFasta.py EOG8RR93M
cp splitFasta.py EOG8RR93Z
cp splitFasta.py EOG8RR944
cp splitFasta.py EOG8RV5BJ
cp splitFasta.py EOG8RV5BM
cp splitFasta.py EOG8RV5BR
cp splitFasta.py EOG8RV5BW
cp splitFasta.py EOG8RV5C0
cp splitFasta.py EOG8RZ1KF
cp splitFasta.py EOG8RZ1KH
cp splitFasta.py EOG8RZ1KJ
cp splitFasta.py EOG8RZ1KM
cp splitFasta.py EOG8RZ1KS
cp splitFasta.py EOG8RZ1KT
cp splitFasta.py EOG8RZ1KZ
cp splitFasta.py EOG8RZ1M0
cp splitFasta.py EOG8RZ1M1
cp splitFasta.py EOG8S1WT8
cp splitFasta.py EOG8S1WTC
cp splitFasta.py EOG8S1WTM
cp splitFasta.py EOG8S1WTR
cp splitFasta.py EOG8S1WV1
cp splitFasta.py EOG8S1WV6
cp splitFasta.py EOG8S4S2C
cp splitFasta.py EOG8S4S2J
cp splitFasta.py EOG8S4S2N
cp splitFasta.py EOG8S4S2Q
cp splitFasta.py EOG8S7N96
cp splitFasta.py EOG8S7N99
cp splitFasta.py EOG8S7N9D
cp splitFasta.py EOG8S7N9F
cp splitFasta.py EOG8S7N9K
cp splitFasta.py EOG8S7N9N
cp splitFasta.py EOG8S7N9P
cp splitFasta.py EOG8S7N9V
cp splitFasta.py EOG8SBHJ1
cp splitFasta.py EOG8SBHJ2
cp splitFasta.py EOG8SBHJ3
cp splitFasta.py EOG8SBHJ6
cp splitFasta.py EOG8SBHJ7
cp splitFasta.py EOG8SBHJB
cp splitFasta.py EOG8SBHJF
cp splitFasta.py EOG8SBHJV
cp splitFasta.py EOG8SBHK1
cp splitFasta.py EOG8SFCS3
cp splitFasta.py EOG8SFCS4
cp splitFasta.py EOG8SFCS8
cp splitFasta.py EOG8SFCSB
cp splitFasta.py EOG8SFCSC
cp splitFasta.py EOG8SFCSF
cp splitFasta.py EOG8SJ810
cp splitFasta.py EOG8SJ812
cp splitFasta.py EOG8SJ813
cp splitFasta.py EOG8SJ814
cp splitFasta.py EOG8SJ816
cp splitFasta.py EOG8SJ81B
cp splitFasta.py EOG8SJ81C
cp splitFasta.py EOG8SJ81D
cp splitFasta.py EOG8SJ81J
cp splitFasta.py EOG8SN47X
cp splitFasta.py EOG8SN47Z
cp splitFasta.py EOG8SN481
cp splitFasta.py EOG8SN482
cp splitFasta.py EOG8SN483
cp splitFasta.py EOG8SN487
cp splitFasta.py EOG8SN488
cp splitFasta.py EOG8SN489
cp splitFasta.py EOG8SN48G
cp splitFasta.py EOG8SN48J
cp splitFasta.py EOG8SN48N
cp splitFasta.py EOG8SR0GT
cp splitFasta.py EOG8SR0GV
cp splitFasta.py EOG8SR0H2
cp splitFasta.py EOG8SR0HB
cp splitFasta.py EOG8SR0HC
cp splitFasta.py EOG8SR0HQ
cp splitFasta.py EOG8STVQR
cp splitFasta.py EOG8STVQW
cp splitFasta.py EOG8STVR0
cp splitFasta.py EOG8STVR1
cp splitFasta.py EOG8STVR3
cp splitFasta.py EOG8STVR4
cp splitFasta.py EOG8SXQZM
cp splitFasta.py EOG8SXQZP
cp splitFasta.py EOG8SXQZR
cp splitFasta.py EOG8SXQZZ
cp splitFasta.py EOG8SXR00
cp splitFasta.py EOG8SXR09
cp splitFasta.py EOG8SXR0C
cp splitFasta.py EOG8T1M6M
cp splitFasta.py EOG8T1M6P
cp splitFasta.py EOG8T1M6T
cp splitFasta.py EOG8T1M6V
cp splitFasta.py EOG8T1M70
cp splitFasta.py EOG8T1M75
cp splitFasta.py EOG8T4GFM
cp splitFasta.py EOG8T4GFR
cp splitFasta.py EOG8T4GFS
cp splitFasta.py EOG8T7BPQ
cp splitFasta.py EOG8T7BPR
cp splitFasta.py EOG8T7BPV
cp splitFasta.py EOG8TB6XF
cp splitFasta.py EOG8TB6XH
cp splitFasta.py EOG8TB6XR
cp splitFasta.py EOG8TB6XZ
cp splitFasta.py EOG8TB6Z7
cp splitFasta.py EOG8TF35D
cp splitFasta.py EOG8TF35F
cp splitFasta.py EOG8TF35J
cp splitFasta.py EOG8TF35K
cp splitFasta.py EOG8TF35S
cp splitFasta.py EOG8TF35T
cp splitFasta.py EOG8TF35X
cp splitFasta.py EOG8TF362
cp splitFasta.py EOG8TF364
cp splitFasta.py EOG8THZD8
cp splitFasta.py EOG8THZD9
cp splitFasta.py EOG8THZDM
cp splitFasta.py EOG8THZDQ
cp splitFasta.py EOG8THZDV
cp splitFasta.py EOG8TMTN6
cp splitFasta.py EOG8TMTN9
cp splitFasta.py EOG8TMTNF
cp splitFasta.py EOG8TMTNM
cp splitFasta.py EOG8TMTNP
cp splitFasta.py EOG8TMTNS
cp splitFasta.py EOG8TQPW4
cp splitFasta.py EOG8TQPWB
cp splitFasta.py EOG8TQPWM
cp splitFasta.py EOG8TTK48
cp splitFasta.py EOG8TTK4D
cp splitFasta.py EOG8TTK4F
cp splitFasta.py EOG8TTK4K
cp splitFasta.py EOG8TXFC5
cp splitFasta.py EOG8TXFC8
cp splitFasta.py EOG8TXFC9
cp splitFasta.py EOG8TXFCD
cp splitFasta.py EOG8TXFCM
cp splitFasta.py EOG8V19M1
cp splitFasta.py EOG8V19M5
cp splitFasta.py EOG8V19MF
cp splitFasta.py EOG8V19MG
cp splitFasta.py EOG8V45TT
cp splitFasta.py EOG8V45TW
cp splitFasta.py EOG8V45TZ
cp splitFasta.py EOG8V45V0
cp splitFasta.py EOG8V45V1
cp splitFasta.py EOG8V45V2
cp splitFasta.py EOG8V45V3
cp splitFasta.py EOG8V45V7
cp splitFasta.py EOG8V45V9
cp splitFasta.py EOG8V45VD
cp splitFasta.py EOG8V45VG
cp splitFasta.py EOG8V722T
cp splitFasta.py EOG8V722X
cp splitFasta.py EOG8V722Z
cp splitFasta.py EOG8V7231
cp splitFasta.py EOG8V7232
cp splitFasta.py EOG8V9X9V
cp splitFasta.py EOG8V9XB2
cp splitFasta.py EOG8V9XB7
cp splitFasta.py EOG8V9XB8
cp splitFasta.py EOG8V9XBB
cp splitFasta.py EOG8VDSJP
cp splitFasta.py EOG8VDSJT
cp splitFasta.py EOG8VDSK0
cp splitFasta.py EOG8VDSK4
cp splitFasta.py EOG8VDSK6
cp splitFasta.py EOG8VDSKF
cp splitFasta.py EOG8VHNSN
cp splitFasta.py EOG8VHNST
cp splitFasta.py EOG8VHNSW
cp splitFasta.py EOG8VHNSX
cp splitFasta.py EOG8VHNSZ
cp splitFasta.py EOG8VHNT1
cp splitFasta.py EOG8VHNTC
cp splitFasta.py EOG8VMJ1H
cp splitFasta.py EOG8VMJ1J
cp splitFasta.py EOG8VMJ1S
cp splitFasta.py EOG8VMJ22
cp splitFasta.py EOG8VMJ2B
cp splitFasta.py EOG8VQD8C
cp splitFasta.py EOG8VQD8F
cp splitFasta.py EOG8VQD8G
cp splitFasta.py EOG8VQD92
cp splitFasta.py EOG8VT8HC
cp splitFasta.py EOG8VT8HD
cp splitFasta.py EOG8VT8HG
cp splitFasta.py EOG8VT8HN
cp splitFasta.py EOG8VT8HP
cp splitFasta.py EOG8VT8HQ
cp splitFasta.py EOG8VT8HW
cp splitFasta.py EOG8VT8J7
cp splitFasta.py EOG8VX4RB
cp splitFasta.py EOG8VX4RC
cp splitFasta.py EOG8VX4RD
cp splitFasta.py EOG8VX4RK
cp splitFasta.py EOG8VX4RM
cp splitFasta.py EOG8VX4RS
cp splitFasta.py EOG8VX4RX
cp splitFasta.py EOG8VX4S0
cp splitFasta.py EOG8VX4S3
cp splitFasta.py EOG8VX4S5
cp splitFasta.py EOG8VX4S6
cp splitFasta.py EOG8W1107
cp splitFasta.py EOG8W110G
cp splitFasta.py EOG8W110Q
cp splitFasta.py EOG8W110R
cp splitFasta.py EOG8W110S
cp splitFasta.py EOG8W110X
cp splitFasta.py EOG8W3W74
cp splitFasta.py EOG8W3W75
cp splitFasta.py EOG8W3W76
cp splitFasta.py EOG8W3W77
cp splitFasta.py EOG8W3W79
cp splitFasta.py EOG8W3W7B
cp splitFasta.py EOG8W3W7C
cp splitFasta.py EOG8W3W7D
cp splitFasta.py EOG8W3W7F
cp splitFasta.py EOG8W3W7G
cp splitFasta.py EOG8W3W7M
cp splitFasta.py EOG8W3W7Q
cp splitFasta.py EOG8W3W7T
cp splitFasta.py EOG8W3W84
cp splitFasta.py EOG8W6RG5
cp splitFasta.py EOG8W6RG6
cp splitFasta.py EOG8W6RG9
cp splitFasta.py EOG8W6RGD
cp splitFasta.py EOG8W6RGF
cp splitFasta.py EOG8W6RGH
cp splitFasta.py EOG8W6RGK
cp splitFasta.py EOG8W6RGM
cp splitFasta.py EOG8W9MQ2
cp splitFasta.py EOG8W9MQ3
cp splitFasta.py EOG8W9MQ4
cp splitFasta.py EOG8W9MQD
cp splitFasta.py EOG8W9MQN
cp splitFasta.py EOG8W9MQS
cp splitFasta.py EOG8WDGXW
cp splitFasta.py EOG8WDGXZ
cp splitFasta.py EOG8WDGZ1
cp splitFasta.py EOG8WDGZ2
cp splitFasta.py EOG8WDGZ3
cp splitFasta.py EOG8WDGZ9
cp splitFasta.py EOG8WDGZD
cp splitFasta.py EOG8WHC5X
cp splitFasta.py EOG8WHC5Z
cp splitFasta.py EOG8WHC60
cp splitFasta.py EOG8WHC64
cp splitFasta.py EOG8WHC68
cp splitFasta.py EOG8WHC6P
cp splitFasta.py EOG8WHC6S
cp splitFasta.py EOG8WM7DT
cp splitFasta.py EOG8WM7DV
cp splitFasta.py EOG8WM7DX
cp splitFasta.py EOG8WM7DZ
cp splitFasta.py EOG8WM7F6
cp splitFasta.py EOG8WM7FC
cp splitFasta.py EOG8WM7FJ
cp splitFasta.py EOG8WM7FM
cp splitFasta.py EOG8WM7FN
cp splitFasta.py EOG8WM7FR
cp splitFasta.py EOG8WQ3NW
cp splitFasta.py EOG8WQ3P6
cp splitFasta.py EOG8WQ3PN
cp splitFasta.py EOG8WSZWT
cp splitFasta.py EOG8WSZWV
cp splitFasta.py EOG8WSZWZ
cp splitFasta.py EOG8WSZX4
cp splitFasta.py EOG8WSZX6
cp splitFasta.py EOG8WSZX9
cp splitFasta.py EOG8WSZXH
cp splitFasta.py EOG8WWV4S
cp splitFasta.py EOG8WWV4X
cp splitFasta.py EOG8WWV51
cp splitFasta.py EOG8WWV54
cp splitFasta.py EOG8WWV56
cp splitFasta.py EOG8WWV57
cp splitFasta.py EOG8WWV5D
cp splitFasta.py EOG8WWV5G
cp splitFasta.py EOG8X0QCH
cp splitFasta.py EOG8X0QCN
cp splitFasta.py EOG8X0QCP
cp splitFasta.py EOG8X0QCQ
cp splitFasta.py EOG8X0QCR
cp splitFasta.py EOG8X0QCS
cp splitFasta.py EOG8X0QCW
cp splitFasta.py EOG8X0QCZ
cp splitFasta.py EOG8X0QD1
cp splitFasta.py EOG8X0QD2
cp splitFasta.py EOG8X0QD5
cp splitFasta.py EOG8X3KMJ
cp splitFasta.py EOG8X3KMK
cp splitFasta.py EOG8X3KMM
cp splitFasta.py EOG8X3KMQ
cp splitFasta.py EOG8X3KMR
cp splitFasta.py EOG8X3KMT
cp splitFasta.py EOG8X3KN3
cp splitFasta.py EOG8X6FVJ
cp splitFasta.py EOG8X6FVK
cp splitFasta.py EOG8X6FVM
cp splitFasta.py EOG8X6FVN
cp splitFasta.py EOG8X6FVP
cp splitFasta.py EOG8X6FVV
cp splitFasta.py EOG8X6FVZ
cp splitFasta.py EOG8X6FW0
cp splitFasta.py EOG8X9B39
cp splitFasta.py EOG8X9B3D
cp splitFasta.py EOG8X9B3F
cp splitFasta.py EOG8X9B3G
cp splitFasta.py EOG8X9B3H
cp splitFasta.py EOG8X9B3M
cp splitFasta.py EOG8X9B3V
cp splitFasta.py EOG8X9B41
cp splitFasta.py EOG8XD6B5
cp splitFasta.py EOG8XD6B7
cp splitFasta.py EOG8XD6BC
cp splitFasta.py EOG8XD6BD
cp splitFasta.py EOG8XD6BF
cp splitFasta.py EOG8XD6BJ
cp splitFasta.py EOG8XD6BM
cp splitFasta.py EOG8XH2K9
cp splitFasta.py EOG8XH2KC
cp splitFasta.py EOG8XH2KG
cp splitFasta.py EOG8XH2KH
cp splitFasta.py EOG8XH2KJ
cp splitFasta.py EOG8XH2KM
cp splitFasta.py EOG8XH2KN
cp splitFasta.py EOG8XH2KR
cp splitFasta.py EOG8XH2KS
cp splitFasta.py EOG8XH2KW
cp splitFasta.py EOG8XH2M1
cp splitFasta.py EOG8XKXT2
cp splitFasta.py EOG8XKXT3
cp splitFasta.py EOG8XKXT7
cp splitFasta.py EOG8XKXT8
cp splitFasta.py EOG8XKXTC
cp splitFasta.py EOG8XKXTM
cp splitFasta.py EOG8XKXV0
cp splitFasta.py EOG8XPT27
cp splitFasta.py EOG8XPT2D
cp splitFasta.py EOG8XPT2M
cp splitFasta.py EOG8XPT2T
cp splitFasta.py EOG8XPT2W
cp splitFasta.py EOG8XSP91
cp splitFasta.py EOG8XSP93
cp splitFasta.py EOG8XSP98
cp splitFasta.py EOG8XSP99
cp splitFasta.py EOG8XSP9D
cp splitFasta.py EOG8XSP9H
cp splitFasta.py EOG8XSP9K
cp splitFasta.py EOG8XSP9R
cp splitFasta.py EOG8XWJHX
cp splitFasta.py EOG8XWJHZ
cp splitFasta.py EOG8XWJJ0
cp splitFasta.py EOG8XWJJ2
cp splitFasta.py EOG8XWJJ4
cp splitFasta.py EOG8XWJJ5
cp splitFasta.py EOG8XWJJ9
cp splitFasta.py EOG8XWJJD
cp splitFasta.py EOG8XWJJF
cp splitFasta.py EOG8XWJJT
cp splitFasta.py EOG8Z0DRV
cp splitFasta.py EOG8Z0DS0
cp splitFasta.py EOG8Z0DS2
cp splitFasta.py EOG8Z0DS4
cp splitFasta.py EOG8Z0DS8
cp splitFasta.py EOG8Z0DSB
cp splitFasta.py EOG8Z0DSC
cp splitFasta.py EOG8Z0DSG
cp splitFasta.py EOG8Z0DSH
cp splitFasta.py EOG8Z390W
cp splitFasta.py EOG8Z3911
cp splitFasta.py EOG8Z3914
cp splitFasta.py EOG8Z3916
cp splitFasta.py EOG8Z3917
cp splitFasta.py EOG8Z3919
cp splitFasta.py EOG8Z391C
cp splitFasta.py EOG8Z391D
cp splitFasta.py EOG8Z391N
cp splitFasta.py EOG8Z657R
cp splitFasta.py EOG8Z657S
cp splitFasta.py EOG8Z657V
cp splitFasta.py EOG8Z657Z
cp splitFasta.py EOG8Z6583
cp splitFasta.py EOG8Z6584
cp splitFasta.py EOG8Z6585
cp splitFasta.py EOG8Z6588
cp splitFasta.py EOG8Z6589
cp splitFasta.py EOG8Z658G
cp splitFasta.py EOG8Z658H
cp splitFasta.py EOG8Z91GP
cp splitFasta.py EOG8Z91GR
cp splitFasta.py EOG8Z91GT
cp splitFasta.py EOG8ZCWQP
cp splitFasta.py EOG8ZCWQQ
cp splitFasta.py EOG8ZCWQR
cp splitFasta.py EOG8ZCWQS
cp splitFasta.py EOG8ZCWQX
cp splitFasta.py EOG8ZCWRB
cp splitFasta.py EOG8ZGRZF
cp splitFasta.py EOG8ZGRZH
cp splitFasta.py EOG8ZGRZJ
cp splitFasta.py EOG8ZGRZK
cp splitFasta.py EOG8ZGRZM
cp splitFasta.py EOG8ZGRZP
cp splitFasta.py EOG8ZGRZS
cp splitFasta.py EOG8ZGRZV
cp splitFasta.py EOG8ZGRZW
cp splitFasta.py EOG8ZGRZZ
cp splitFasta.py EOG8ZKN6Z
cp splitFasta.py EOG8ZKN73
cp splitFasta.py EOG8ZKN79
cp splitFasta.py EOG8ZPHFF
cp splitFasta.py EOG8ZPHFM
cp splitFasta.py EOG8ZPHFS
cp splitFasta.py EOG8ZPHFV
cp splitFasta.py EOG8ZPHFX
cp splitFasta.py EOG8ZPHFZ
cp splitFasta.py EOG8ZPHG1
cp splitFasta.py EOG8ZPHG7
cp splitFasta.py EOG8ZPHG8
cp splitFasta.py EOG8ZSCPB
cp splitFasta.py EOG8ZSCPC
cp splitFasta.py EOG8ZSCPD
cp splitFasta.py EOG8ZSCPF
cp splitFasta.py EOG8ZSCPG
cp splitFasta.py EOG8ZSCPH
cp splitFasta.py EOG8ZSCPX
cp splitFasta.py EOG8ZSCQ4
cp splitFasta.py EOG8ZW7X7
cp splitFasta.py EOG8ZW7X9
cp splitFasta.py EOG8ZW7XD
cp splitFasta.py EOG8ZW7XF
cp splitFasta.py EOG8ZW7XH
cp splitFasta.py EOG8ZW7XJ
cp splitFasta.py EOG8ZW7XK
cp splitFasta.py EOG8ZW7XN
cp splitFasta.py EOG8ZW7XR
cp splitFasta.py EOG8ZW7Z4
